config:
  aws:region: us-east-1
  # Required: Set these values for your deployment
  # opencloud-infra:domainName: cloud.your-domain.com
  # opencloud-infra:hostedZoneId: Z1234567890ABC
  # opencloud-infra:adminPassword:
  #   secure: <run: pulumi config set --secret adminPassword YourSecurePassword>
  # opencloud-infra:acmeEmail: admin@your-domain.com
  #
  # Optional configuration
  # opencloud-infra:instanceType: t3.medium
  # opencloud-infra:keyName: your-ssh-key-name
